#' Access the OpenAI GPT API to generate text completions
#' 
#' This function sends a request to the OpenAI GPT API to generate text completions for a given prompt.
#' 
#' https://platform.openai.com/docs/api-reference
#' 
#' @param prompt a character string representing the prompt for which to generate text completions
#' @param api_key a character string representing the API key to use to access the OpenAI GPT API
#' 
#' @return a character string representing the text completion generated by the API in response to the prompt
#' 
#' @examples 
#' api_key <- "sk-YOUR_API_KEY" 
#' prompt <- "Can you write a poem about my cat Sam?"
#' response <- access_gpt(prompt, api_key)
# Save API key
api_key <- "sk-YOUR_API_KEY" 

# Load packages
library(httr)
library(stringr)

# Define ask_chatgpt function outside of gpt function
access_gpt <- function(prompt, api_key) {
  response <- POST(
    url = "https://api.openai.com/v1/chat/completions", 
    add_headers(Authorization = paste("Bearer", api_key)),
    content_type_json(),
    encode = "json",
    body = list(
      model = "gpt-3.5-turbo",
      messages = list(list(
        role = "user", 
        content = prompt
      ))
    )
  )
  str_trim(content(response)$choices[[1]]$message$content)
}
#' Generate text completions using the OpenAI GPT API
#' 
#' This function generates text completions for a given prompt using the OpenAI GPT API. It returns a function that can be used to generate text completions for multiple prompts.
#' 
#' @param api_key a character string representing the API key to use to access the OpenAI GPT API
#' 
#' @return a function that takes a character string as input and returns a character string representing the text completion generated by the API in response to the input
#' 
#' @examples 
#' api_key <- "sk-YOUR_API_KEY" 
#' ask_gpt <- gpt_api(api_key)
#' prompt <- "Can you write a poem about my cat Sam?"
#' result <- ask_gpt(prompt)
# Save gpt function
gpt_api <- function(api_key) {
  ask <- function(prompt) {
    access_gpt(prompt, api_key)
  }
  
  return(ask)
}