#' Fit an ARIMA model to the AirPassengers dataset and make a forecast
#'
#' The auto.arima model uses a stepwise selection method. This function presents an 
#' iterative approach where all permutations of the ARIMA components are tested.
#' This script is meant for illustrative purposes.
#'
#' @param data The AirPassengers dataset
#' @param p_values The range of AR order values to search
#' @param d_values The range of differencing values to search
#' @param q_values The range of MA order values to search
#' @param P_values The range of seasonal AR order values to search
#' @param D_values The range of seasonal differencing values to search
#' @param Q_values The range of seasonal MA order values to search
#'
#' @return A forecast object generated by the best-fit ARIMA model
#'
#' @examples
#' \dontrun{
#' # Load the AirPassengers data
#' data("AirPassengers")
#'
#' # Split the data into training and test sets
#' train <- window(AirPassengers, end = c(1958, 12))
#' test <- window(AirPassengers, start = c(1959, 1))
#'
#' # Fit an ARIMA model and make a forecast
#' forecast <- fit_arima(AirPassengers, p_values = c(0, 1, 2), d_values = c(0, 1),
#'                       q_values = c(0, 1, 2), P_values = c(0, 1, 2), D_values = c(0, 1),
#'                       Q_values = c(0, 1, 2))
#' }
# Load package
library(forecast)

# Load example data
data("AirPassengers")

# Split the data into training and test sets
train <- window(AirPassengers, end = c(1958, 12))
test <- window(AirPassengers, start = c(1959, 1))

# Define the grid of parameter values to search
p_values <- c(0, 1, 2)
d_values <- c(0, 1)
q_values <- c(0, 1, 2)
P_values <- c(0, 1, 2)
D_values <- c(0, 1)
Q_values <- c(0, 1, 2)

# Initialize a variable to store the best model
best_model <- NULL
best_aic <- Inf

# Loop over all possible parameter combinations
for (p in p_values) {
  for (d in d_values) {
    for (q in q_values) {
      for (P in P_values) {
        for (D in D_values) {
          for (Q in Q_values) {
            
            # Fit the model
            model <- auto.arima(train, start.p = p, d = d, start.q = q,
                                max.p = max(p_values), max.d = max(d_values), max.q = max(q_values),
                                seasonal = TRUE, start.P = P, D = D, start.Q = Q,
                                max.P = max(P_values), max.D = max(D_values), max.Q = max(Q_values),
                                stepwise = FALSE, approximation = FALSE, trace = FALSE)
            
            # Calculate the AIC
            aic <- AIC(model)
            
            # Update the best model if this one has a lower AIC
            if (aic < best_aic) {
              best_model <- model
              best_aic <- aic
            }
          }
        }
      }
    }
  }
}

# Make a forecast using the best model
forecast <- forecast(best_model, h = 12)

# Plot the forecast
plot(forecast, main = "AirPassengers Forecast")

# Calculate the forecast accuracy on the test set
accuracy <- accuracy(forecast, test)

# Print the best model and its AIC
print(best_model)
cat("Best AIC:", best_aic, "\n")

# Print the forecast accuracy
print(accuracy)